{% set name = "Orange3-Survival-Analysis" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4b2df41f40e38204e0fb233fe45baec58e5c73755384a35fe9d83cd97ab512d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - Orange3 >=3.32
    - lifelines
    - statsmodels
    - pyqt
    - pyqtgraph

test:
  requires:
    - python {{ python_min }}
  imports:
    - orangecontrib.survival_analysis

about:
  home: http://orange.biolab.si/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Survival Analysis add-on for Orange3 data mining suite
  description: |
    Orange3 Survival Analysis add-on for the Orange3 data mining suite.
  # todo: add when available: doc_url
  dev_url: https://github.com/biolab/orange3-survival-analysis

extra:
  recipe-maintainers:
    - primozgodec
    - markotoplak
    - JakaKokosar
